@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Contêiner - MediAgro

Person(usuario, "Usuário", "Responsável pelo controle sanitário dos animais.")

System_Boundary(mediagro, "MediAgro") {

    Container(web, "Aplicação Web", "Python, Flask, HTML, CSS", "Permite cadastrar, listar, editar e excluir animais, vacinações e manejos sanitários, além de visualizar o Dashboard.")

    ContainerDb(banco, "Banco de Dados", "SQLite", "Armazena os dados de animais, vacinações e manejos sanitários.")
}

Rel(usuario, web, "Utiliza", "Navegador Web")
Rel(web, banco, "Lê e grava dados")

@enduml