@startuml

title Modelo de Banco de Dados - AgroVita

entity "animais" as animais {
    * id : INTEGER <<PK>>
    --
    identificacao : TEXT
    especie : TEXT
    raca : TEXT
    data_nascimento : TEXT
}

entity "vacinacoes" as vacinacoes {
    * id : INTEGER <<PK>>
    --
    animal : TEXT
    vacina : TEXT
    lote : TEXT
    fabricante : TEXT
    data_aplicacao : TEXT
    proxima_dose : TEXT
    dose : TEXT
    responsavel : TEXT
    observacoes : TEXT
}

entity "manejos" as manejos {
    * id : INTEGER <<PK>>
    --
    animal : TEXT
    tipo_manejo : TEXT
    data_manejo : TEXT
    produto : TEXT
    dose : TEXT
    responsavel : TEXT
    observacoes : TEXT
}

@enduml